### ISSUE TITLE
wails dev does not load the page

### ISSUE THREAD

**Issue by mschneider82** [PylotLight/wails-hmtx-templ#4]
running wails dev in the project dir looks incomplete:

![image](https://github.com/PylotLight/wails-htmx-templ-template/assets/8426497/45672cea-a639-4bc7-92c2-8c19fcc10638)

the browser view looks fine, even the wails build version looks good. Do you know whats the issue with the gui when running wails dev?

**Comment by PylotLight** [comment]
Looks like you're running in linux, did you try with this tag mentioned in the readme?
> For Linux build tag webkit2_40 is required

**Comment by mschneider82** [comment]
a thank you, `wails dev -tags webkit2_40` did the job.
