### ISSUE TITLE
Can this work for non GET requests

### ISSUE THREAD

**Issue by emiago** [PylotLight/wails-hmtx-templ#6]
Although in this example has POST routes, I am failing to see this works due to wails asset is only served via GET?

I am not expert in wails, but would like to use htmx to build app. So I would like to know limitations or are there some workarround?

**Comment by PylotLight** [comment]
This is why the chi routing is used to handle any requests that the asset handler can't serve.
Feel free to join us on the wails discord for discussion.

**Comment by emiago** [comment]
ok posted there. Closing this.
