### ISSUE TITLE
wails dev: The process cannot access the file because it is being used by another process

### ISSUE THREAD

**Issue by JAndritsch** [PylotLight/wails-hmtx-templ#7]
Hi there!

Thanks for putting together this template. I'm excited to get started using HTMX+Templ with Wails. Unfortunately, I seem to be encountering an error when trying to run `wails dev`. The README says to run both that as well as the command to start up the frontend server. 

However, it looks like `wails dev` is potentially doing both at the same time and causing the following error for me on Windows:

```
Wails CLI v2.8.0

Executing: go mod tidy
  • Generating bindings: Done.
  • Installing frontend dependencies: Done.
  • Compiling frontend: Done.
$ bun -b --hot vite

  VITE v4.5.3  ready in 422 ms

Vite Server URL: http://localhost:5173/
  ➜  Local:   http://localhost:5173/
  ➜  Network: use --host to expose
Running frontend DevWatcher command: 'bun run dev'
Building application for development...
  • Generating bindings: 
Build error - 
2024/03/30 09:04:41 remove C:\Users\joel\dev\go-wails-templ-htmx-example\frontend\wailsjs\go: The process cannot access the file because it is being used by another process.

exit status 1
No version running, build will be retriggered as soon as changes have been detected
Using DevServer URL: http://localhost:34115
Using Frontend DevServer URL: http://localhost:5173/
Using reload debounce setting of 100 milliseconds
Watching (sub)/directory: C:\Users\joel\dev\go-wails-templ-htmx-example


To develop in the browser and call your bound Go methods from Javascript, navigate to: http://localhost:34115
```

It seems there are multiple processes that are attempting to access the `wailsjs/go` folder. Is `bun` maybe beating `wails` to it and then preventing `wails` from doing its thing? I have no idea, just guessing here.

Let me know if there's any more info I can provide. I'm using the latest version of your template (as of today) and the most recent version of Wails (2.8.0) on Windows 11.

**Comment by JAndritsch** [comment]
Looks like the fix here is this change, then running both `wails dev` and `bun run dev` in separate terminals as per the README:

```diff
diff --git a/wails.json b/wails.json
index 43c503a..b01a785 100644
--- a/wails.json
+++ b/wails.json
@@ -4,8 +4,6 @@
   "outputfilename": "go-wails-templ-htmx-example",
   "frontend:install": "bun install",
   "frontend:build": "bun run build",
-  "frontend:dev:watcher": "bun run dev",
-  "frontend:dev:serverUrl": "auto",
   "author": {
```

**Comment by JAndritsch** [comment]
Also, running these commands separately means you now have to provide `wails dev` with the URL for the frontend server, otherwise hot reloading won't work:

```
wails dev -frontenddevserverurl http://localhost:5173/
```

**Comment by JAndritsch** [comment]
I've been fiddling with this on and off throughout the day and discovered that any changes made to Go code result in a reload of Wails (good), but doing that reload results in the same error above when you have `bun run dev` still up. This means you have to stop the bun server and then restart both processes anytime you change something (bad).

It seems `bun` is the issue here. I switched to using `npm` and `vite` directly via these changes:

```diff
diff --git a/frontend/package.json b/frontend/package.json
index d50fbed..71e484a 100644
--- a/frontend/package.json
+++ b/frontend/package.json
@@ -10,9 +10,9 @@
   },
   "private": true,
   "scripts": {
-    "dev": "bun -b --hot vite",
-    "build": "bun -b vite build",
-    "preview": "bun -b vite preview"
+    "dev": "vite",
+    "build": "vite build",
+    "preview": "vite preview"

diff --git a/wails.json b/wails.json
index b01a785..faf447b 100644
--- a/wails.json
+++ b/wails.json
@@ -2,8 +2,10 @@
   "$schema": "https://wails.io/schemas/config.v2.json",
   "name": "go-wails-templ-htmx-example",
   "outputfilename": "go-wails-templ-htmx-example",
-  "frontend:install": "bun install",
-  "frontend:build": "bun run build",
+  "frontend:install": "npm install",
+  "frontend:build": "npm run build",
+  "frontend:dev:watcher": "npm run dev",
+  "frontend:dev:serverUrl": "auto",
```

Now I'm able to just run `wails dev` and have it handle both the Wails side as well as the frontend side.

**Comment by PylotLight** [comment]
I already have an npm build under @npm tag if you wanted to try that.

Also yes wails dev should run both so don't need to run frontend separately.

**Comment by JAndritsch** [comment]
> I already have an npm build under @npm tag if you wanted to try that.

That looks like it should work. The tag has the same changes that I made above.

Is this something you think is easily fixable, or should I close the issue given there's a workaround in using `npm`?

**Comment by PylotLight** [comment]
I haven't seen any issues on my end with these templates so not convinced there's anything to fix given the available tags.

**Comment by JAndritsch** [comment]
> I haven't seen any issues on my end with these templates so not convinced there's anything to fix given the available tags.

I wonder if this is a Windows-specific issue. I'm guessing you're on Mac or Linux?

Either way, I'll close it out since the problem isn't really with the template.

**Comment by PylotLight** [comment]
Ah yep I use WSL sorry.
If you do have any windows specific fixes let me know and I can update the readme or something =]
