### ISSUE TITLE
Loading index from chi

### ISSUE THREAD

**Issue by EduardoOliveira** [PylotLight/wails-hmtx-templ#8]
Hi there,
Have you font a way to load a route as default page instead of index.html?

I'm trying to develop a application that should work both as a self hosted service and desktop application.
I currently have a full state management in the URL of the page, loading the initial request from an html file with hx-gets will make it hard to keep path state. For instance /lib/objID/details that obj is would have to be parsed by js and used to modify the hx-gets... Not as smooth as I would want....

If you have any insight that would be perfect, if not, I'll just keep hacking and report back.

Thanks for your project

**Comment by PylotLight** [comment]
I don't use chi anymore as of 1.22 but you could just use hx-trigger="load" or something no?
Probably better to join the discord to discuss routing management as there's no specific issue here, cheers.
